/**
 * Extra source files to watch per documentation page (merged with route-derived `page.tsx`).
 * When these files change, quick-reference + in-depth guides for that page must be reviewed.
 */
export const USER_DOC_SUPPLEMENTAL_WATCH_PATHS: Readonly<Record<string, readonly string[]>> = {
  homepage: [
    "src/components/app-top-nav.tsx",
    "src/components/auth-buttons.tsx",
    "src/components/sign-up-dialog.tsx",
    "src/components/account-recovery-fields.tsx",
    "src/actions/account-recovery-profile.ts",
    "src/app/onboarding/account-recovery/page.tsx",
  ],
  "header-navigation": [
    "src/components/app-top-nav.tsx",
    "src/components/header-user-section.tsx",
  ],
  "team-workspace-dashboard": ["src/app/dashboard/workspace/page.tsx"],
  "deck-editor": [
    "src/app/decks/[deckId]/page.tsx",
    "src/app/decks/[deckId]/card-grid.tsx",
    "src/components/edit-deck-dialog.tsx",
    "src/app/decks/[deckId]/generate-cards-button.tsx",
    "src/app/decks/[deckId]/add-card-dialog.tsx",
    "src/app/decks/[deckId]/edit-card-dialog.tsx",
    "src/app/decks/[deckId]/answer-choice-image-control.tsx",
    "src/app/decks/[deckId]/ai-generate-popover.tsx",
    "src/app/decks/[deckId]/from-source-card-form.tsx",
    "src/actions/cards.ts",
    "src/lib/math-diagrams/schema.ts",
    "src/lib/math-diagrams/render.ts",
    "src/app/api/ai/card-diagram/route.ts",
  ],
  "personal-dashboard": ["src/components/offline-availability-button.tsx"],
  "offline-mobile": [
    "src/components/offline-availability-button.tsx",
    "src/components/offline-banner.tsx",
    "src/components/native-notification-bootstrap.tsx",
    "src/components/native-app-bootstrap.tsx",
    "src/components/service-worker-register.tsx",
    "src/lib/native-notifications/push-registration.ts",
    "src/lib/native-notifications/push-handlers.ts",
    "src/lib/native-notifications/inbox-poller.ts",
    "src/lib/native-notifications/update-checker.ts",
    "src/lib/native-push.ts",
    "src/lib/notify-native-inbox-push.ts",
    "src/app/api/native/push-register/route.ts",
    "src/app/api/native/deploy-version/route.ts",
    "src/app/api/native/app-version/route.ts",
    "src/app/api/inbox/unread-count/route.ts",
    "src/lib/use-online-status.ts",
    "src/lib/offline/sync.ts",
    "src/lib/offline/repository.ts",
    "src/lib/offline/session.ts",
    "src/app/api/sync/route.ts",
    "src/actions/offline-sync.ts",
    "src/app/native-signin/native-signin-client.tsx",
    "src/app/native-signin/page.tsx",
    "src/app/api/native/clerk-handoff/route.ts",
    "src/components/account-recovery-fields.tsx",
    "src/actions/account-recovery-profile.ts",
  ],
  "study-session": [
    "src/app/decks/[deckId]/study/page.tsx",
    "src/app/decks/[deckId]/study/flashcard-study.tsx",
    "src/app/decks/[deckId]/study/quiz-study.tsx",
    "src/components/format-quiz-question-dialog.tsx",
    "src/actions/quiz-formats.ts",
    "src/lib/quiz-formats.ts",
    "src/lib/quiz-questions.ts",
    "src/lib/quiz-format-assignments.ts",
    "src/lib/education-plans.ts",
  ],
  "quiz-result-detail": [
    "src/app/dashboard/quiz-results/[resultId]/page.tsx",
    "src/components/quiz-result-detail-view.tsx",
    "src/lib/quiz-pdf-server.ts",
  ],
  inbox: [
    "src/components/inbox-unified-client.tsx",
    "src/app/dashboard/inbox/page.tsx",
    "src/lib/record-welcome-inbox.ts",
    "src/components/login-welcome-toast.tsx",
  ],
  "help-center-overview": ["src/components/help-center.tsx"],
  "help-center-support": ["src/components/help-center.tsx", "src/components/contact-support-view.tsx"],
  "help-center-bug-report": ["src/components/help-center.tsx"],
  "help-center-feature-request": ["src/components/help-center.tsx"],
  "help-center-feedback": ["src/components/help-center.tsx"],
  "help-center-billing": ["src/components/help-center.tsx"],
  "help-center-account": ["src/components/help-center.tsx"],
  "help-center-my-tickets": ["src/components/help-center-my-tickets.tsx"],
  "help-center-priority-support": ["src/components/help-center.tsx"],
  "contact-us-page": ["src/components/contact-support-view.tsx"],
  "contact-us-live-chat": ["src/components/contact-support-view.tsx", "src/components/contact-us-thread-view.tsx"],
  "contact-us-guest-vs-signed-in": ["src/components/contact-support-view.tsx"],
  "contact-us-vs-help-center": ["src/components/contact-support-view.tsx", "src/components/help-center.tsx"],
  pricing: ["src/components/pricing-content.tsx", "src/data/plans-config.json"],
  "stripe-billing-payment": [
    "src/actions/stripe.ts",
    "src/components/stripe-checkout-button.tsx",
    "src/app/api/webhooks/stripe/route.ts",
  ],
  checkout: ["src/app/pricing/checkout/page.tsx", "src/actions/stripe.ts"],
  "manage-subscription": ["src/components/user-billing-page.tsx", "src/components/manage-billing-button.tsx"],
  "prorations-plan-changes": ["src/actions/stripe.ts", "src/app/pricing/checkout/plan-change/pay/page.tsx"],
  "promo-general": ["src/data/plans-config.json", "src/components/pricing-content.tsx"],
  "promo-affiliate": ["src/components/affiliate-portal-view.tsx", "src/data/plans-config.json"],
  "promo-seasonal-by-plan": ["src/data/plans-config.json"],
  "clerk-profile": [
    "src/components/header-user-section.tsx",
    "src/actions/account-recovery-profile.ts",
    "src/lib/account-recovery-profile.ts",
    "src/app/onboarding/account-recovery/page.tsx",
  ],
  "account-details-settings": [
    "src/components/header-user-section.tsx",
    "src/components/user-account-details-page.tsx",
    "src/components/account-recovery-fields.tsx",
    "src/actions/account-recovery-profile.ts",
  ],
  "appearance-settings": ["src/components/header-user-section.tsx"],
  "billing-tab": ["src/components/user-billing-page.tsx", "src/actions/stripe.ts"],
  "account-delete": ["src/components/account-delete-dialog.tsx"],
  "team-admin-overview": [
    "src/components/team-admin-manage-tabs.tsx",
    "src/components/team-admin-quick-nav-panel.tsx",
  ],
  members: [
    "src/components/team-admin-invitation-tables.tsx",
    "src/components/team-member-table.tsx",
    "src/actions/teams.ts",
  ],
  "deck-manager": [
    "src/components/team-deck-assign-list.tsx",
    "src/components/team-deck-manager-sub-tabs.tsx",
    "src/components/team-quiz-formats-settings.tsx",
    "src/app/dashboard/(team-admin)/team-admin/deck-manager/study-privileges/page.tsx",
    "src/actions/quiz-formats.ts",
    "src/lib/generate-quiz-variants-ai.ts",
    "src/lib/quiz-format-assignments.ts",
  ],
  "invite-members": [
    "src/app/dashboard/(team-admin)/team-admin/invite-members/pending-invitations/page.tsx",
    "src/app/dashboard/(team-admin)/team-admin/invite-members/invitation-history/page.tsx",
  ],
  "quiz-results-admin": [
    "src/app/dashboard/(team-admin)/team-admin/quiz-results/quiz-security/page.tsx",
    "src/app/dashboard/(team-admin)/team-admin/quiz-results/quiz-timer/page.tsx",
    "src/app/dashboard/(team-admin)/team-admin/quiz-results/quiz-schedule/page.tsx",
  ],
  "affiliate-dashboard": ["src/components/affiliate-portal-view.tsx", "src/components/affiliate-invite-inbox-section.tsx"],
  "education-plans": [
    "src/data/plans-config.json",
    "src/components/pricing-content.tsx",
    "src/lib/education-plans.ts",
  ],
  "teacher-dashboard": [
    "src/app/teacher/page.tsx",
    "src/components/teacher-dashboard-home.tsx",
    "src/components/teacher-dashboard-shell.tsx",
    "src/lib/teacher-dashboard-nav.ts",
    "src/lib/teacher-access.ts",
  ],
  "teacher-ai-content-tools": [
    "src/app/teacher/lesson-builder/page.tsx",
    "src/app/teacher/quizzes/page.tsx",
    "src/app/teacher/homework/page.tsx",
    "src/app/teacher/study-guides/page.tsx",
    "src/app/teacher/worksheets/page.tsx",
    "src/lib/teacher-dashboard-nav.ts",
  ],
  "teacher-classroom": [
    "src/app/teacher/classes/page.tsx",
    "src/app/teacher/students/page.tsx",
  ],
  "teacher-resources": ["src/app/teacher/resources/page.tsx"],
};

export const ADMIN_DOC_SUPPLEMENTAL_WATCH_PATHS: Readonly<Record<string, readonly string[]>> = {
  "admin-dashboard-overview": [
    "src/components/admin-overview-stats-collapsible.tsx",
    "src/lib/admin/load-admin-dashboard-data.ts",
    "src/components/admin-dashboard-shell.tsx",
    "src/components/admin-dashboard-nav.tsx",
    "src/lib/admin-dashboard-nav.ts",
    "src/app/admin/layout.tsx",
  ],
  "all-users": [
    "src/lib/admin/serialize-admin-users.ts",
    "src/lib/admin-user-account-details.ts",
    "src/actions/admin.ts",
    "src/components/admin-tabs.tsx",
    "src/db/queries/admin.ts",
  ],
  subscription: ["src/lib/admin/admin-billing-snapshot.ts", "src/db/queries/stripe-subscriptions.ts"],
  invoices: ["src/db/queries/billing.ts"],
  "paid-subscribers": ["src/lib/admin-user-plan-label.ts", "src/db/queries/billing.ts"],
  "team-workspaces": ["src/db/queries/admin.ts"],
  "admin-roles": ["src/actions/admin.ts", "src/lib/platform-superadmin.ts"],
  "audit-log": ["src/db/queries/admin.ts"],
  "support-tickets": ["src/components/admin-support-panel.tsx", "src/db/queries/support.ts"],
  "support-contact-us": [
    "src/components/admin-contact-us-panel.tsx",
    "src/components/admin-contact-us-thread-panel.tsx",
    "src/db/queries/contact-us.ts",
  ],
  "pricing-plans": ["src/components/admin-plans-editor.tsx", "src/data/plans-config.json"],
  "plan-history": ["src/db/queries/admin.ts"],
  "affiliate-messaging": ["src/components/admin-affiliate-promo-broadcast.tsx"],
  "marketing-affiliates": [
    "src/components/admin-affiliates-panel.tsx",
    "src/components/admin-affiliate-quota-panel.tsx",
    "src/db/queries/affiliates.ts",
  ],
  "plan-trials": [
    "src/components/admin-plan-trial-settings.tsx",
    "src/lib/plan-trial.ts",
    "src/data/plans-config.json",
    "src/db/queries/user-plan-trials.ts",
  ],
  "documentation-manager": [
    "src/components/platform-documentation-manager.tsx",
    "src/components/documentation-agent-panel.tsx",
    "src/components/documentation-edit-sheet.tsx",
    "src/actions/documentation-agent.ts",
    "src/actions/documentation-admin.ts",
    "src/db/queries/documentation-overrides.ts",
  ],
};

/** Shared shell for every admin guide page. */
export const ADMIN_DOC_SHARED_WATCH_PATHS: readonly string[] = [
  "src/components/admin-tabs.tsx",
  "src/lib/admin-dashboard-section.ts",
  "src/components/admin-dashboard-shell.tsx",
  "src/lib/admin-dashboard-nav.ts",
];
